Repository StackStorm/stackstorm-k8s, pull requests merged in 2018-10, with the labels that each got.

#25 Add Helm & K8s Lint checks
  .circleci/config.yml
  Chart.yaml
  README.md
  templates/configmaps_rbac.yaml
  values.yaml
Labels: RFR

#26 StackStorm Community HA
  .circleci/config.yml
  CHANGELOG.md
  Chart.yaml
  README.md
  templates/NOTES.txt
  templates/_helpers.tpl
  templates/configmaps_packs.yaml
  templates/configmaps_rbac.yaml
  templates/configmaps_st2-conf.yaml
  templates/configmaps_st2-urls.yaml
  templates/deployments.yaml
  templates/jobs.yaml
  templates/secrets_ssh.yaml
  templates/secrets_st2auth.yaml
  templates/secrets_st2license.yaml
  templates/secrets_st2web.yaml
  templates/services.yaml
  values.yaml
Labels: RFR, feature, support:community

#29 Include a link to st2-dockerfiles github repo
  README.md
Labels: RFR, documentation

#30 Helm 'st2.keyvalue' to import data into st2 K/V storage
  CHANGELOG.md
  templates/jobs.yaml
  templates/secrets_st2kv.yaml
  values.yaml
Labels: RFR, feature

#32 Add new st2 service st2scheduler
  CHANGELOG.md
  Chart.yaml
  README.md
  templates/deployments.yaml
  values.yaml
Labels: RFR, feature
