Repository StackStorm/stackstorm-k8s, pull requests merged in 2018-11, with the labels that each got.

#33 Fix st2web re-deployment is not triggered when updating SSL cert
  CHANGELOG.md
  Chart.yaml
  templates/deployments.yaml
Labels: RFR, bug

#34 Add LoadBalancer type to st2web service
  .gitignore
  CHANGELOG.md
  Chart.yaml
  requirements.yaml
  templates/NOTES.txt
  templates/services.yaml
  values.yaml
Labels: Helm, K8s, WIP

#38 Add checksum/packs annotation to a few services
  CHANGELOG.md
  Chart.yaml
  templates/deployments.yaml
Labels: Helm, RFR, enhancement, st2

#39 Fix LoadBalancer templating to utilize correct service endpoints in NOTES
  CHANGELOG.md
  Chart.yaml
  templates/NOTES.txt
Labels: RFR, bug
