Repository StackStorm/stackstorm-k8s, pull requests merged in 2018-09, with the labels that each got.

#15 Update links to Github Issues
  templates/deployments.yaml
  templates/etcd.yaml
  templates/ingress.yaml
  templates/jobs.yaml
  values.yaml
Labels: RFR, documentation

#20 Replace ASCII art
  templates/NOTES.txt
Labels: RFR

#21 Bundle some defaults into original st2.conf
  CHANGELOG.md
  Chart.yaml
  templates/configmaps_st2-conf.yaml
Labels: Docker, K8s, RFR
