Repository StackStorm/stackstorm-k8s, pull requests merged in 2019-04, with the labels that each got.

#55 Chatops integration
  .gitignore
  CHANGELOG.md
  Chart.yaml
  README.md
  templates/deployments.yaml
  templates/secrets_st2chatops.yaml
  templates/services.yaml
  values.yaml
Labels: RFR, feature

#64 Add missing documentation for st2scheduler
  README.md
Labels: RFR, documentation

#66 Move st2web.annotations into st2web.service
  CHANGELOG.md
  Chart.yaml
  templates/services.yaml
Labels: bug
