Repository StackStorm/stackstorm-k8s, pull requests merged in 2019-02, with the labels that each got.

#46 Fix reference to socat image
  README.md
Labels: bug, documentation

#47 Update README with corrected case for username
  README.md
Labels: bug, documentation

#48 Rename socat repo
  README.md
Labels: RFR, enhancement

#45 Add new Helm value setting 'st2.apikeys' to import ST2 API keys
  CHANGELOG.md
  Chart.yaml
  templates/jobs.yaml
  templates/secrets_st2apikeys.yaml
  values.yaml
Labels: feature
