Repository StackStorm/stackstorm-k8s, pull requests merged in 2019-05, with the labels that each got.

#67 Use st2 3.1dev
  CHANGELOG.md
  Chart.yaml
Labels: CI/CD, RFR, st2

#69 Add a README with pattern of extending stackstorm-ha Helm chart
  README.md
Labels: documentation, enhancement

#70 Setup K8s infrastructure for Helm e2e tests
  .circleci/config.yml
  README.md
Labels: CI/CD, feature

#68 Add support for ingress
  CHANGELOG.md
  Chart.yaml
  README.md
  templates/NOTES.txt
  templates/ingress.yaml
  values.yaml
Labels: WIP, enhancement

#72 Replace st2web https with http
  .circleci/config.yml
  CHANGELOG.md
  Chart.yaml
  README.md
  templates/NOTES.txt
  templates/deployments.yaml
  templates/ingress.yaml
  templates/secrets_st2web.yaml
  templates/services.yaml
  values.yaml
Labels: Helm, RFR, feature
