Repository StackStorm/stackstorm-k8s, pull requests merged in 2019-03, with the labels that each got.

#52 HA for etcd
  CHANGELOG.md
  README.md
  requirements.yaml
  templates/etcd.yaml
  values.yaml
Labels: RFR, enhancement

#53 Fix improper job load order for enterprise edition
  CHANGELOG.md
  templates/jobs.yaml
Labels: Helm, RFR, bug, support:enterprise

#51 Allow st2sensorcontainer to be partitioned
  CHANGELOG.md
  README.md
  templates/_helpers.tpl
  templates/deployments.yaml
  values.yaml
Labels: Docker, Helm, K8s, RFR, enhancement
