Repository StackStorm/stackstorm-k8s, pull requests merged in 2020-02, with the labels that each got.

#108 Added templating capability for st2kv from values
  CHANGELOG.md
  templates/secrets_st2kv.yaml
  values.yaml
Labels: enhancement, size/XS

#103 Fix st2web ingress
  templates/ingress.yaml
Labels: enhancement, size/XS

#109 Prepare release for v0.24.0
  CHANGELOG.md
  Chart.yaml
  values.yaml
Labels: feature, size/S

#111 Fix/Ingress servicePort
  CHANGELOG.md
  templates/ingress.yaml
Labels: size/XS

#112 Update ingress.yaml
  CHANGELOG.md
  templates/ingress.yaml
Labels: enhancement, size/XS

#114 Allow injecting of hostAliases in the actionrunner deployment
  CHANGELOG.md
  templates/deployments.yaml
  values.yaml
Labels: enhancement, size/XS
