Repository StackStorm/stackstorm-k8s, pull requests merged in 2020-12, with the labels that each got.

#157 Release v0.40.0: Switch chart to latest st2 3.4dev version, disable Enterprise
  .circleci/config.yml
  CHANGELOG.md
  Chart.yaml
  README.md
  templates/NOTES.txt
Labels: enhancement, size/M

#164 New Location For Stable Charts
  .circleci/config.yml
  CHANGELOG.md
  Chart.yaml
  requirements.yaml
Labels: Helm, size/S

#163 Migrate to Helm v3, Change dependencies from deprecated official helm charts to Bitnami charts
  .circleci/config.yml
  CHANGELOG.md
  Chart.yaml
  README.md
  conf/rabbit-definition.conf
  requirements.yaml
  templates/_helpers.tpl
  templates/configmaps_st2-conf.yaml
  templates/secrets_rabbitmq.yaml
  templates/tests/st2tests-pod.yaml
  values.yaml
Labels: breaking change, enhancement, feature, size/L
