Repository StackStorm/stackstorm-k8s, pull requests merged in 2021-09, with the labels that each got.

#240 fix chatops deployment indentation
  templates/deployments.yaml
Labels: bug, RFR, size/M

#239 imagePullSecrets is a top-level attribute of ServiceAccounts
  CHANGELOG.md
  templates/service-account.yaml
Labels: bug, RFR, size/XS

#244 version bump: 0.70.0
  CHANGELOG.md
  Chart.yaml
Labels: size/XS

#222 Clarify the distinction between sensor modes: all-sensors-in-one-pod and one-sensor-per-pod
  CHANGELOG.md
  templates/deployments.yaml
  values.yaml
Labels: enhancement, Helm, RFR, size/S

#120 Allow injection of env vars in any deployment
  CHANGELOG.md
  templates/_helpers.tpl
  templates/deployments.yaml
  templates/jobs.yaml
  values.yaml
Labels: enhancement, size/M

#249 Template the contents of st2.config and the values in st2chatops.env.
  CHANGELOG.md
  templates/configmaps_st2-conf.yaml
  templates/secrets_st2chatops.yaml
  values.yaml
Labels: enhancement, Helm, RFR, size/XS

#248 Allow excluding default/sample RBAC files in values
  CHANGELOG.md
  templates/configmaps_rbac.yaml
  values.yaml
Labels: enhancement, Helm, size/S

#246 Improve one-sensor-per-pod UX: require "ref" in st2.packs.sensors
  CHANGELOG.md
  templates/deployments.yaml
  values.yaml
Labels: enhancement, Helm, RFR, size/M, breaking change

#253 Use "--convert" when loading keys into datastore
  CHANGELOG.md
  templates/jobs.yaml
Labels: enhancement, RFR, st2, size/XS

#254 Feature: custom volumes (for secrets, etc) on st2actionrunner pods
  CHANGELOG.md
  templates/deployments.yaml
  values.yaml
Labels: feature, K8s, size/M
