Repository StackStorm/stackstorm-k8s, pull requests merged in 2021-02, with the labels that each got.

#176 Publish stackstorm-ha Helm chart on Artifact Hub
  Chart.yaml
  README.md
Labels: feature, size/XS

#178 Introduced initContainers to wait for DB/MQ availability
  CHANGELOG.md
  templates/_helpers.tpl
  templates/deployments.yaml
  templates/jobs.yaml
Labels: enhancement, size/M

#179 Added resource Requests values for St2 Pods
  CHANGELOG.md
  values.yaml
Labels: enhancement, size/M

#183 Release stackstorm-ha v0.52.0
  CHANGELOG.md
  Chart.yaml
Labels: size/XS
