Repository StackStorm/stackstorm-k8s, pull requests merged in 2021-11, with the labels that each got.

#263 Included nodeSelector, affinity and tolerations to st2client deployment
  CHANGELOG.md
  templates/deployments.yaml
  values.yaml
Labels: enhancement, size/S

#262 template st2client conf
  CHANGELOG.md
  templates/deployments.yaml
  templates/jobs.yaml
  values.yaml
Labels: enhancement, Helm, RFR, size/M

#268 fix st2web.postStartScript indent
  CHANGELOG.md
  templates/deployments.yaml
Labels: bug, Helm, size/XS

#264 Allow st2web to serve HTTPS
  CHANGELOG.md
  templates/deployments.yaml
  templates/services.yaml
  values.yaml
Labels: feature, Docker, K8s, security, size/M
