Repository StackStorm/stackstorm-k8s, pull requests merged in 2021-12, with the labels that each got.

#270 apply annotations to deployments and jobs, not just pods
  CHANGELOG.md
  templates/deployments.yaml
  templates/jobs.yaml
Labels: enhancement, K8s, size/M

#266 Generate datastore_crypto_key on install if not provided
  .circleci/config.yml
  CHANGELOG.md
  README.md
  conf/datastore_crypto_key.yaml
  templates/configmaps_st2-conf.yaml
  templates/deployments.yaml
  templates/secrets_datastore_crypto_key.yaml
  values.yaml
Labels: feature, security, size/M, breaking change

#274 Bump st2 version to v3.6
  CHANGELOG.md
  Chart.yaml
Labels: size/XS

#275 bump to version 0.80.0
  CHANGELOG.md
  Chart.yaml
Labels: size/XS

#271 Add securityContext and podSecurityContext values
  CHANGELOG.md
  templates/_helpers.tpl
  templates/deployments.yaml
  templates/jobs.yaml
  values.yaml
Labels: feature, K8s, size/L
