Repository StackStorm/stackstorm-k8s, pull requests merged in 2021-03, with the labels that each got.

#166 Allow multiple packs images
  CHANGELOG.md
  README.md
  templates/_helpers.tpl
  templates/deployments.yaml
  templates/jobs.yaml
  values.yaml
Labels: breaking change, enhancement, size/L

#182 Refactor Helm templates to configure LDAP/RBAC as OSS, remove Enterprise (v3.4)
  .circleci/config.yml
  CHANGELOG.md
  Chart.yaml
  templates/NOTES.txt
  templates/_helpers.tpl
  templates/configmaps_packs.yaml
  templates/configmaps_rbac.yaml
  templates/configmaps_st2-conf.yaml
  templates/configmaps_st2-urls.yaml
  templates/configmaps_st2web.yaml
  templates/deployments.yaml
  templates/ingress.yaml
  templates/jobs.yaml
  templates/secrets_datastore_crypto_key.yaml
  templates/secrets_rabbitmq.yaml
  templates/secrets_ssh.yaml
  templates/secrets_st2apikeys.yaml
  templates/secrets_st2auth.yaml
  templates/secrets_st2chatops.yaml
  templates/secrets_st2kv.yaml
  templates/secrets_st2license.yaml
  templates/services.yaml
  templates/tests/st2tests-pod.yaml
  tests/st2tests.sh
  values.yaml
Labels: CI/CD, enhancement, feature, size/L

#190 Issue 188: st2rulesengine references datastore_crypto_key incorrectly
  CHANGELOG.md
  templates/deployments.yaml
Labels: bug, size/XS

#187 Release new Chart v0.60.0 with st2 3.5dev
  CHANGELOG.md
  Chart.yaml
Labels: size/XS
