Repository StackStorm/stackstorm-k8s, pull requests merged in 2021-07, with the labels that each got.

#207 Add optional (advanced-only) hubot-scripts volume to st2chatops pod
  CHANGELOG.md
  templates/deployments.yaml
  values.yaml
Labels: RFR, feature, size/S

#215 yaml template style: use nindent to follow yaml indentation
  templates/deployments.yaml
  templates/ingress.yaml
  templates/jobs.yaml
  templates/service-account.yaml
  templates/services.yaml
Labels: Helm, RFR, enhancement, size/L

#193 Allow adding nodeSelector, affinity, tolerations to batch Jobs
  CHANGELOG.md
  templates/jobs.yaml
  values.yaml
Labels: Helm, K8s, RFR, feature, size/M

#216 yaml template style: use nindent for nodeSelector, affinity, tolerations
  templates/deployments.yaml
Labels: Helm, RFR, enhancement, size/L

#203 Refactor secrets and auto-generate password + ssh_key
  .circleci/config.yml
  CHANGELOG.md
  templates/NOTES.txt
  templates/configmaps_st2-conf.yaml
  templates/deployments.yaml
  templates/secrets_datastore_crypto_key.yaml
  templates/secrets_ssh.yaml
  templates/secrets_st2auth.yaml
  values.yaml
Labels: RFR, breaking change, feature, security, size/L

#198 Refactor: Use helper for st2-config-vol volume/volumeMounts definitions
  CHANGELOG.md
  templates/_helpers.tpl
  templates/deployments.yaml
  templates/jobs.yaml
Labels: Helm, RFR, enhancement, size/L

#219 Fix stanley_rsa permissions via postStart pod lifecycle hook
  CHANGELOG.md
  templates/configmaps_post-start-script.yaml
  templates/deployments.yaml
  tests/st2tests.sh
Labels: RFR, enhancement, security, size/M

#217 reformat: drop trailing spaces
  README.md
  templates/_helpers.tpl
  templates/configmaps_st2-conf.yaml
  templates/deployments.yaml
  templates/secrets_rabbitmq.yaml
  templates/secrets_st2chatops.yaml
  values.yaml
Labels: Helm, RFR, size/S

#220 Make system_user "stanley" configurable
  CHANGELOG.md
  templates/configmaps_post-start-script.yaml
  templates/configmaps_st2-conf.yaml
  templates/deployments.yaml
  values.yaml
Labels: Helm, RFR, feature, size/M, st2

#206 Allow adding postStartScript lifecycle hook to all deployments
  CHANGELOG.md
  templates/configmaps_post-start-script.yaml
  templates/deployments.yaml
  values.yaml
Labels: K8s, RFR, feature, size/L

#213 Add preRegisterContentCommand in an initContainer for register-content job
  CHANGELOG.md
  templates/jobs.yaml
  values.yaml
Labels: RFR, feature, size/S

#224 Fix : mount datastore_cryto_key volumne on st2rulesengine deployment #223
  CHANGELOG.md
  templates/deployments.yaml
Labels: RFR, bug, size/XS

#221 Make st2.packs.sensors pull default values from st2sensorcontainer
  CHANGELOG.md
  templates/deployments.yaml
  values.yaml
Labels: Helm, RFR, feature, size/M
