Repository StackStorm/stackstorm-k8s, pull requests merged in 2022-05, with the labels that each got.

#304 Upgrade to MongoDB v4.4
  CHANGELOG.md
  values.yaml
Labels: enhancement, size/XS, maintenance

#282 feat: add CHANGELOG entry for container version bump to Python 3.8 / …
  CHANGELOG.md
  Chart.yaml
  tests/integration/st2tests.sh
Labels: size/XS

#307 Issue #306 : Adding the ability to use overrides
  CHANGELOG.md
  templates/_helpers.tpl
  templates/configmaps_overrides.yaml
  templates/deployments.yaml
  templates/jobs.yaml
  tests/unit/custom_annotations_test.yaml
  tests/unit/dns_test.yaml
  tests/unit/env_test.yaml
  tests/unit/image_pull_test.yaml
  tests/unit/labels_test.yaml
  tests/unit/overrides_test.yaml
  tests/unit/packs_volumes_test.yaml
  tests/unit/placement_test.yaml
  tests/unit/post_start_script_test.yaml
  tests/unit/resources_test.yaml
  tests/unit/security_context_test.yaml
  tests/unit/service_account_test.yaml
  tests/unit/st2sensors_test.yaml
  values.yaml
Labels: feature, size/L

#308 Bump to v0.100.0
  .circleci/config.yml
  CHANGELOG.md
  Chart.yaml
Labels: size/XS
