Repository StackStorm/stackstorm-k8s, pull requests merged in 2022-01, with the labels that each got.

#279 fix nil securityContext in packs-initContainers
  templates/_helpers.tpl
Labels: bug, size/XS

#272 Standardize helper comments and names (prefix all helper names with stackstorm-ha)
  CHANGELOG.md
  templates/_helpers.tpl
  templates/configmaps_st2-conf.yaml
  templates/deployments.yaml
  templates/jobs.yaml
  templates/tests/st2tests-pod.yaml
Labels: Helm, size/L

#280 Fixes reference to password value in st2 auth secret.
  templates/NOTES.txt
Labels: size/XS
