Repository StackStorm/stackstorm-k8s, pull requests merged in 2022-03, with the labels that each got.

#288 Add unit tests for a variety of chart aspects
  .github/workflows/unit-tests.yaml
  CHANGELOG.md
  tests/README.md
  tests/unit/custom_annotations_test.yaml
  tests/unit/dns_test.yaml
  tests/unit/image_pull_test.yaml
  tests/unit/labels_test.yaml
  tests/unit/placement_test.yaml
  tests/unit/post_start_script_test.yaml
  tests/unit/resources_test.yaml
  tests/unit/security_context_test.yaml
  tests/unit/service_account_test.yaml
  tests/unit/st2sensors_test.yaml
Labels: CI/CD, Helm, size/XXL

#218 Allow partitioning sensors with hash ranges across multiple deployments instead of one-sensor-per-pod
  CHANGELOG.md
  README.md
  templates/deployments.yaml
  tests/unit/st2sensors_test.yaml
  values.yaml
Labels: feature, RFR, status:feedback needed, size/L, status:to be verified

#291 Allow "external" st2api, st2auth, and st2stream Services (LoadBalancer type with hostname)
  CHANGELOG.md
  templates/services.yaml
  tests/unit/custom_annotations_test.yaml
  tests/unit/services_test.yaml
  values.yaml
Labels: enhancement, K8s, size/L

#296 Update comment to show GC acts on action output by default.
  values.yaml
Labels: size/XS

#292 Add unit tests for env, envFrom, st2.packs.images, and st2.packs.volumes
  CHANGELOG.md
  templates/deployments.yaml
  tests/unit/env_test.yaml
  tests/unit/packs_volumes_test.yaml
Labels: CI/CD, Helm, size/XXL

#265 Enable extra post-install and post-upgrade helm-hook jobs for environment-specific config
  CHANGELOG.md
  README.md
  templates/jobs.yaml
  tests/unit/custom_annotations_test.yaml
  tests/unit/dns_test.yaml
  tests/unit/env_test.yaml
  tests/unit/image_pull_test.yaml
  tests/unit/labels_test.yaml
  tests/unit/packs_volumes_test.yaml
  tests/unit/placement_test.yaml
  tests/unit/security_context_test.yaml
  values.yaml
Labels: feature, Helm, size/L
