Repository StackStorm/stackstorm-k8s, pull requests merged in 2022-04, with the labels that each got.

#298 bump to v0.90.0
  CHANGELOG.md
  Chart.yaml
  README.md
  values.yaml
Labels: size/S

#300 Fix CI status badge
  README.md
Labels: size/XS

#303 Add missing LICENSE file
  LICENSE
Labels: documentation, size/L
