Repository StackStorm/stackstorm-k8s, pull requests merged in 2022-07, with the labels that each got.

#301 Ingress api version deprecation support for k8s v.1.22. fixes #277
  CHANGELOG.md
  templates/ingress.yaml
  tests/unit/ingress_test.yaml
Labels: size/L

#322 Fix `jobs.preRegisterContentCommand` init container mounts
  CHANGELOG.md
  templates/jobs.yaml
Labels: bug, Helm, size/S

#141 support for custom st2actionrunner images via values.yaml
  CHANGELOG.md
  templates/deployments.yaml
  tests/unit/image_pull_test.yaml
  tests/unit/image_test.yaml
  values.yaml
Labels: enhancement, size/XL

#324 Address issue with register content when configuring volumes
  CHANGELOG.md
  templates/_helpers.tpl
Labels: bug, Helm, size/XS
