Repository StackStorm/stackstorm-k8s, pull requests merged in 2023-01, with the labels that each got.

#346 CI: Cover the three most recent Kubernetes versions in Minikube and the single most recent in K3s
  .circleci/config.yml
  .github/workflows/e2e.yaml
  CHANGELOG.md
  README.md
Labels: enhancement, CI/CD, size/M

#348 Bump the st2 version to latest v3.8.0
  CHANGELOG.md
  Chart.yaml
Labels: size/XS, maintenance

#352 Bump to v0.110.0
  CHANGELOG.md
  Chart.yaml
Labels: size/XS, maintenance

#353 Remove support for networking.k8s.io/v1beta1 removed in k8s v1.22 (already EOL)
  CHANGELOG.md
  templates/ingress.yaml
  tests/unit/ingress_test.yaml
Labels: bug, Helm, K8s, size/M, maintenance

#351 Standardize Resource Labels
  CHANGELOG.md
  README.md
  migrations/v1.0/standardize-labels.sh
  templates/NOTES.txt
  templates/_helpers.tpl
  templates/configmaps_overrides.yaml
  tests/unit/labels_test.yaml
  tests/unit/st2sensors_test.yaml
Labels: Helm, K8s, size/L, breaking change

#354 refactor tests to simplify / DRY label tests
  CHANGELOG.md
  tests/unit/labels_test.yaml
Labels: enhancement, size/L
