Repository StackStorm/stackstorm-k8s, pull requests merged in 2023-02, with the labels that each got.

#358 CI: Shift K3s and K8s versions forward
  .circleci/config.yml
  .github/workflows/e2e.yaml
  CHANGELOG.md
Labels: size/XS

#323 add an st2canary pod that validates st2.packs.volumes
  CHANGELOG.md
  templates/_helpers.tpl
  templates/jobs.yaml
  tests/unit/custom_annotations_test.yaml
  tests/unit/dns_test.yaml
  tests/unit/labels_test.yaml
  tests/unit/packs_volumes_test.yaml
  tests/unit/placement_test.yaml
  tests/unit/security_context_test.yaml
  values.yaml
Labels: feature, Helm, K8s, size/L

#356 configurable utilityImage + clusterDomain and increase default db timeouts to avoid replicaset timeout
  templates/_helpers.tpl
  templates/deployments.yaml
  templates/jobs.yaml
  values.yaml
Labels: size/M
