Repository StackStorm/stackstorm-k8s, pull requests merged in 2024-01, with the labels that each got.

#382 Presleep for st2auth, st2web, st2api, st2stream
  templates/deployments.yaml
  values.yaml
Labels: size/S

#383 Update the Chart Maintainers - the StackStorm Authors
  Chart.yaml
Labels: size/XS

#385 Secret DataStore Crypto Key should not be created when existing provided
  templates/secrets_datastore_crypto_key.yaml
  tests/unit/secrets_test.yaml
Labels: size/L
