Repository StackStorm/stackstorm-k8s, pull requests merged in 2024-04, with the labels that each got.

#410 add securityContext for more containers with better fallbacks
  CHANGELOG.md
  templates/_helpers.tpl
  templates/deployments.yaml
  templates/jobs.yaml
  tests/unit/security_context_test.yaml
  values.yaml
Labels: enhancement, size/L

#404 Update README.md to fix mispelling of volumes
  README.md
Labels: documentation, size/XS

#391 Remove data store key labels when not generating the secret
  CHANGELOG.md
  templates/deployments.yaml
Labels: size/S

#392 Stop generating the checksum labels for Auth Secret when existing secret provided
  CHANGELOG.md
  templates/deployments.yaml
Labels: enhancement, K8s, size/XS

#398 Add image pull policy to all containers
  CHANGELOG.md
  templates/_helpers.tpl
  templates/deployments.yaml
  templates/jobs.yaml
Labels: size/XS

#411 fix script in job-st2canary-for-writable-packs-volume
  CHANGELOG.md
  templates/jobs.yaml
Labels: bug, K8s, RFR, size/XS

#413 Add `image.entrypoint` value to support custom entrypoints like `dumb-init`
  CHANGELOG.md
  templates/_helpers.tpl
  templates/deployments.yaml
  tests/unit/image_entrypoint_test.yaml
  values.yaml
Labels: bug, Docker, RFR, size/L

#412 Improve Deployments migration in `migrations/1.0/standardize-labels.sh`
  CHANGELOG.md
  migrations/v1.0/standardize-labels.sh
Labels: enhancement, Helm, K8s, RFR, size/M
