Repository StackStorm/stackstorm-k8s, pull requests merged in 2024-05, with the labels that each got.

#417 Refactor unit tests to support unittests v0.4.4
  .github/workflows/unit.yaml
  CHANGELOG.md
  templates/deployments.yaml
  templates/jobs.yaml
  tests/README.md
  tests/unit/custom_annotations_test.yaml
  tests/unit/dns_test.yaml
  tests/unit/env_test.yaml
  tests/unit/image_entrypoint_test.yaml
  tests/unit/image_pull_test.yaml
  tests/unit/labels_test.yaml
  tests/unit/placement_test.yaml
  tests/unit/post_start_script_test.yaml
  tests/unit/resources_test.yaml
  tests/unit/secrets_test.yaml
  tests/unit/security_context_test.yaml
  tests/unit/service_account_test.yaml
  tests/unit/services_test.yaml
  tests/unit/st2sensors_test.yaml
Labels: CI/CD, size/L

#418 Don't preserve ownership when copying pack contents
  CHANGELOG.md
  templates/_helpers.tpl
Labels: size/S

#421 Bump unittests to v0.5.1
  .github/workflows/unit.yaml
  CHANGELOG.md
  tests/README.md
Labels: size/XS

#420 Migrate to kubeconform for k8s linting, as kubeval is now deprecated
  .github/workflows/lint.yaml
  .kubeconform
  CHANGELOG.md
Labels: size/S
